### ISSUE TITLE
Reduce the number cycles when parsing

### ISSUE THREAD

**Issue by victorsndvg** [szaghi/FLAP#23]
Hello Stefano,

I was looking through the code searching for a bug (I will report it now) and I see that in:

https://github.com/szaghi/FLAP/blob/b135fb872a3c6c9cc9b0e572f639f218fd86cbb1/src/Data_Type_Command_Line_Interface.F90#L1193

The loop continues even after finding the switch in the CLI. The suggestion is to force to stop the loop at this point. I think this would reduce the complexity.

What do you think?

Best regards,
Víctor.

**Comment by szaghi** [comment]
You are right, but I have just strongly refactored this procedure (indeed all procedures).

I am uploading my testing version into a new version on Github repo, so you can see my progress, but this version has a very *testing* status...

**Comment by szaghi** [comment]
Now the procedure is inside the CLAg group and there is the exit statement for reducing the number of cycles:

https://github.com/szaghi/FLAP/blob/master/src/Data_Type_Command_Line_Interface.F90#L1212

**Comment by victorsndvg** [comment]
Good job!
Sorry I think I've been very impatient ;)

**Comment by szaghi** [comment]
No, you are great!

I am too slow... but I am very busy.
