### ISSUE TITLE
Travis issue 

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FLAP#26]
Hi @szaghi, this is not an issue with FLAP, but I was wondering if you could try resubmitting your Travis-CI build. My similar script has started failing at `sudo apt-get update -qq` with error code 139. I'm curious if this issue affects other people trying to use Travis with gfortran-4.9

**Comment by szaghi** [comment]
Sure, I am doing it right now.

**Comment by szaghi** [comment]
Done.

**Comment by zbeekman** [comment]
huh, I can’t seem to figure out which travis job you just resubmitted… any way, thanks for giving it a shot

**Comment by szaghi** [comment]
This one https://travis-ci.org/szaghi/FLAP/builds/63673076

10 hours ago.

**Comment by zbeekman** [comment]
OK…. I’m quite confused as to whats going on with my build right now… maybe it was a temporary issue with travis. Any way, thanks for doing this.

**Comment by szaghi** [comment]
You are always welcime! Good luck!
