### ISSUE TITLE
Check-boxes in documentation

### ISSUE THREAD

**Issue by cmacmackin** [szaghi/FLAP#4]
Heads-up about a new feature which I've added to FORD and will be pushing to the repository soon (once I have the include statement working). You'll be able to supply a list of Markdown extensions which you want to use. [This one](https://pypi.python.org/pypi/markdown-checklist) might be of interest to you, as it allows for the display of check-boxes in the same way as on Github.

**Comment by szaghi** [comment]
Right!

I use it on MaTiSSe.py and it is a very nice extension.
