### ISSUE TITLE
Why multiple README.md?

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FLAP#40]
Hi Stefano,
I’m just curious what your rational of keeping `README.md` and `doc/README-FLAP.md` is. If you want to include it in the FORD documentation is there a reason that either:

 1. A symbolic link
 2. Specifying the path as `../README.md`

won’t work? I think trying one of these approaches might help make your life easier so that you don’t have to remember to update the README.md in two places and `git add` & `git commit` it every time you update it.

**Comment by zbeekman** [comment]
It seems that the symbolic link works. I’ll submit a PR with this, you can accept or reject it.

**Comment by szaghi** [comment]
Hi @zbeekman ,

The problem was that FORD uses main page path as its root, thus for I just like to have docs not into project root. Yes, links work: on my local repo the two readme are hard linked, anyway you are rigth sym link makes paths cleaner.

**Comment by zbeekman** [comment]
merging #42 fixes this
