### ISSUE TITLE
badges and links still point to coveralls

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FLAP#41]
Both the main page of the wiki as well as the README.md still have badges pointing to coveralls rather than codecov. I’ll also post some links here that you can use to adjust your codecov settings that I find useful.

**Comment by szaghi** [comment]
Thanks! Tomorrow I have to do a lot of work...

**Comment by zbeekman** [comment]
Sorry I forgot to update this issue. Merging #42 fixes this issue. Also when you have a chance it might be worthwhile to check out and update some of the codecov.io settings, with my recommendations:

 1. https://codecov.io/github/szaghi/FLAP/features/ignore : add `src/IR_Precision.F90`, `src/Test_Driver.f90`, `src/Test_Driver_Args_From_String.f90` and `src/Test_Driver_Nested.f90` to the ignored files so that the total coverage is only based on `src/Data_Type_Command_Line_Interface.F90` and not the unit tests or unused code in `fIR_Precision.F90`
 1. https://codecov.io/github/szaghi/FLAP/features/comment : turn on everything
 1. https://codecov.io/github/szaghi/FLAP/features/status : project coverage %75, patch coverage %90
