### ISSUE TITLE
git submodule for IR_precision

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FLAP#43]
It might make sense to use a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) for IR_precision rather than duplicating the source into this project and your others. Git submodules can be a little bit confusing at first, but poor Fortran people can be taught how to use them, I think.

**Comment by szaghi** [comment]
@zbeekman 

:-)

You are right (and not the first to advice me... @victorsndvg I am studying your setup...).

ASAP, I will integrate git submodules into my workflow :-)

**Comment by zbeekman** [comment]
If you want me to take a crack at it and submit a PR, let me know. It shouldn’t take long.

**Comment by szaghi** [comment]
@zbeekman Feel free to do anything you consider useful, all your PR are always welcome. 

However, for this specific case I have a dubt (that blocks me to use submodule in all my publuc projects): is possible to *submodularize* just one file of a remote repo? If not, the ir_precision module should be *submodularized* smartly...

**Comment by zbeekman** [comment]
yes, as far as I know you need to use the whole repo not just one file. You can use a symbolic link to simplify the structure though, and keep it similar to how it is now. Or adapt the fobos file to account for the new structure.

**Comment by szaghi** [comment]
Done in the version 0.6.3.

Submodules are placed into external and the necessary sources are symlinked from here
to the main project src directory.

**Comment by victorsndvg** [comment]
Hello @szaghi ,

sorry for my ignorance, but I've seen your recent changes related with this issue and it's the first time that I see symbolic links in git. 

It is a git feature or  an usual symbolic link?

**Comment by szaghi** [comment]
Hi victor, it is a usual sym link. Git can handle the *type* of file and it recognizes that this is a sym link.

I will working on Lib_VTK_IO in my break today...
