### ISSUE TITLE
GH_TOKEN secure variable needs to be added to travis-ci

### ISSUE THREAD

**Issue by zbeekman** [szaghi/FLAP#47]
Hi Stefano, as I mentioned in #45, I think you still need to add a private/secure variable through the Travis-CI repository settings containing a working GH token. See #45 for instructions on how to do this. As you can see in the [latest build](https://travis-ci.org/szaghi/FLAP/builds/69266788#L944) the GH_TOKEN variable appears to be evaluating to the null string, preventing the deployment of the FORD documentation

**Comment by szaghi** [comment]
Sure, I forget to do...

**Comment by zbeekman** [comment]
Can you go to travis and resubmit the [last build](https://travis-ci.org/szaghi/FLAP/builds/69285565) once you’ve added this, just so that we can make sure that everything is now working?

**Comment by szaghi** [comment]
Done, but the deploy seems to not work

**Comment by zbeekman** [comment]
I’ll take a look

**Comment by zbeekman** [comment]
It looks like you named your environment variable something other than `GH_TOKEN`: https://travis-ci.org/szaghi/FLAP/builds/69285565#L91

If you had named it `GH_TOKEN` you would have seen a line like this: https://travis-ci.org/zbeekman/json-fortran/jobs/69347547#L80

Please create secure variable who’s name matches exactly `GH_TOKEN` holding a github token with commit privileges. [makedoc.sh](https://github.com/szaghi/FLAP/blob/master/makedoc.sh) can be modified if you like to use a variable name other than `GH_TOKEN` but please note that bash variables should not have spaces in their name, so your current variable name likely won’t work.

**Comment by szaghi** [comment]
Opssss, I think you are rigth, sorry. Tomorrow I'll fix it! Thank you

**Comment by szaghi** [comment]
Done, thank you @zbeekman !

**Comment by zbeekman** [comment]
No problem, thanks for such a cool project!
