### ISSUE TITLE
Non initialized Error code in parse() procedure

### ISSUE THREAD

**Issue by victorsndvg** [szaghi/FLAP#69]
Hi @szaghi ,

I think there is a bug (in release mode) using FLAP while parsing CLI multiple times. 
If I run the code below, the second time that I call `parse(error)`, `error` value is not initialized from the `parse()` procedure.
```fortran
     type(Command_Line_Interface)  :: cli
     integer :: error
     cli%parse(error)
     ...
     cli%free() 
     ...
     cli%parse(error)
     ...
     cli%free() 
```
I think that there are 2 minor changes to fix this behaviour.
First, force a successful `error` code at the begining of the `parse()` procedure in this line: https://github.com/szaghi/FLAP/blob/master/src/lib/flap_command_line_interface_t.F90#L519
```fortran
    if(present(error)) error = 0  ! <- New line
    if (self%is_parsed_) return
    ...
```

And finally, Set `is_parsed_` variable to `.false.` in the `free()` procedure.

You can see this changes in my FLAP-fork in this commit : https://github.com/victorsndvg/FLAP/commit/a9c201a46b402b5a9d00a9b2db6a815ead0b3722

Do you think I'm right or there is something that I'm missing?

**Comment by szaghi** [comment]
Great @victorsndvg , I'll look into it now!

**Comment by szaghi** [comment]
@victorsndvg  You are right! Just patched! Thank you very much. New master will be uploaded soon.

P.S. I think this is the first test of %free method... I have to expand the tests suite...

**Comment by szaghi** [comment]
@victorsndvg New v1.1.1 pushed. I think your patch is perfect, no other missing issues should be involved, many many thanks!
