### ISSUE TITLE
FLAP compilation system

### ISSUE THREAD

**Issue by victorsndvg** [szaghi/FLAP#7]
Dear Stephano,

first of all I would like to congratulate you for the great work on your projects from github.

I would try FLAP to include it in another project but I don't know how to compile it. Sorry to ask such a basic question but, how could I compile and test FLAP?

Thanks in advance.

Best regards,
Víctor.

**Comment by szaghi** [comment]
Dear Victor,

you are too kind. 

I hope you have read the wiki page where the compilation phase should be explained. The page is the following

https://github.com/szaghi/FLAP/wiki/Compile

In case you have miss this page I can try to summarize:

+ you can build the test driver using [FoBiS.py](https://github.com/szaghi/FoBiS); for example into the root directory where you have cloned FLAP (after you have installed FoBiS) you can type `FoBiS.py build -mode flap-test`;

+ you can build the test driver using GNU Make: for more details see this https://github.com/szaghi/FLAP/wiki/Compile#compiling-without-fobispy; in particular you can copy the makefile showed into the text, copy it into a file named `makefile` and then type `make`; in your system Make must be installed.

I suggest you to start with one of the above system; once you have started one of them, write me on this issue of any problems you find and I will try to help you step by step with the building system you have chosen.

Thank you for trying FLAP.

**Comment by victorsndvg** [comment]
Hello Stephano,

thanks for the quick response. I try to compile using the makefile from  https://github.com/szaghi/FLAP/wiki/Compile#compiling-without-fobispy and it seems that one dependency was forbidden.

Adding a line seem to be enought in:

> $(DOBJ)lib_io_misc.o: src/Lib_IO_Misc.f90 \
> 	$(DOBJ)ir_precision.o 
> 	@echo $(COTEXT)
> 	@$(FC) $(OPTSC) $(PREPROC)  $< -o $@

changing it by:

> $(DOBJ)lib_io_misc.o: src/Lib_IO_Misc.f90 \
> 	**$(DOBJ)lib_strings.o \**
> 	$(DOBJ)ir_precision.o
> 	@echo $(COTEXT)
> 	@$(FC) $(OPTSC) $(PREPROC)  $< -o $@

Thanks again.

Best regards,
Víctor.

**Comment by szaghi** [comment]
Yes, the example into the wiki can be too old (Lib_Strings came after the wiki...).

Does it now compile well?

Thank you for testing the makefile :-)

**Comment by victorsndvg** [comment]
Yes, it works for me :)

**Comment by szaghi** [comment]
Ok, I am closing this issue.

For any other questions feel free to ask me.

Happy Fortran!
