### ISSUE TITLE
Compling error when building with GCC 6.4.0

### ISSUE THREAD

**Issue by xiaocanli** [szaghi/FLAP#79]
Below is the log. It seems to be due to the R16 extension.

Builder options
  Directories
    Building directory: "static"
    Compiled-objects .o   directory: "static/obj"
    Compiled-objects .mod directory: "static/mod"
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-cpp -c -frealloc-lhs -O2 -D_R16P_SUPPORTED"
    Linking flags: ""
    Preprocessing flags: "-D_R16P_SUPPORTED"
    Coverage: False
    Profile: False
  PreForM.py used: False
  PreForM.py output directory: None
  PreForM.py extensions processed: []

Building src/lib/flap.f90
Compiling src/third_party/PENF/src/lib/penf_global_parameters_variables.F90 serially
Compiling src/third_party/PENF/src/lib/penf_b_size.F90 serially
Compiling src/third_party/PENF/src/lib/penf_stringify.F90 serially
Compiling src/third_party/PENF/src/lib/penf.F90 serially
Compiling src/third_party/FACE/src/lib/face.f90 src/lib/flap_object_t.f90 src/lib/flap_utils_m.f90 using 2 concurrent processes
Compiling src/lib/flap_command_line_argument_t.F90 serially
src/lib/flap_command_line_argument_t.F90:52:39:

     generic,   public :: get_varying =>                &
                                       1
Error: ‘get_cla_list_varying_r16p’ and ‘get_cla_list_varying_r8p’ for GENERIC ‘get_varying’ at (1) are ambiguous
(null):0: confused by earlier errors, bailing out

src/lib/flap_command_line_argument_t.F90:52:39:

     generic,   public :: get_varying =>                &
                                       1
Error: ‘get_cla_list_varying_r16p’ and ‘get_cla_list_varying_r8p’ for GENERIC ‘get_varying’ at (1) are ambiguous
(null):0: confused by earlier errors, bailing out

**Comment by szaghi** [comment]
Dear @xiaocanli 

I am sorry for my delay, this is a very busy period. I'll check this bug ASAP.

Thank you very much for pointing it out.

**Comment by szaghi** [comment]
Dear @xiaocanli 

Later today I'll should be able to investigate this issue. Stay tuned.

**Comment by AliE89** [comment]
Hello there, It's been ages, but I am getting the same under gfortran 7.5 :)

**Comment by szaghi** [comment]
@AliE89 

Wow, I missed that this is still live, my bad.

Old versions of compilers are not supported, I am sorry, but I can try to help if the issue is not related to compilers bugs.

Commonly issues related to R16P are related to my flip/flop behavior to support 128bit real kind (due to the fact that some compilers do not support that kind). Currently, I am working a lot with NVFortran that does not support R16P thus I could have introduced some incompatibilities into my libraries.  

Can you give me more details about your issue?

**Comment by AliE89** [comment]
> Hi Stefano,


yes it looks to be alive. I had to remove from the interface the _R16
function to make it work.

**Comment by szaghi** [comment]
@AliE89 

I cannot try old version of GCC. Currently, I am using gcc 10.2.0 and it seems to compile well (at least by means of FoBiS).

**Comment by xiaocanli** [comment]
I have been using it with newer versions of gfortran and ifort without a problem (compiled using FoBis).

**Comment by AliE89** [comment]
Cool, so it is me beign an erethic not using fobis XD thanks for the
feedback guys

**Comment by xiaocanli** [comment]
Since we will not test older versions of gfortran, I would suggest closing this old issue.
@AliE89 Thanks for bringing this up!
@szaghi Thanks for this great library!

**Comment by AliE89** [comment]
Sure, let's close it. I have used gfortran 10.2 as well, a simpky think i
am missing some definitions while using my own makefile, while fobis can
configuration file can deal with it.
