### ISSUE TITLE
PENF breaking in tarball download

### ISSUE THREAD

**Issue by cponder** [szaghi/FLAP#93]
Running these commands
```
curl --retry 5 -fSsL "https://github.com/szaghi/FLAP/archive/refs/tags/v${FLAP_VERSION}.tar.gz" | tar xz
cd FLAP-1.1.8
./scripts/install.sh --build cmake
```
gives me errors like
```
[ 12%] No download step for 'PENF'
[ 18%] No update step for 'PENF'
[ 31%] Performing configure step for 'PENF'
CMake Error: The source directory "/usr/local/src/FLAP-1.1.8/src/third_party/PENF" does not appear to contain CMakeLists.txt.
```
I saw in #80 that the git-fetch is supposed to include it.
But I prefer to use the tarball over GIT since it gives me an identifiable version-tag to reference it with.
Is there some other way to install it?

**Comment by cponder** [comment]
These two tarballs are different:
https://github.com/szaghi/FLAP/archive/refs/tags/v1.1.7.tar.gz
https://github.com/szaghi/FLAP/releases/download/v1.1.7/FLAP-v1.1.7.tar.gz
It looks like the second one is better; the PENF still breaks but I get a library at least:
```
-rw-r--r-- 1 cponder dip 1663862 Dec 22 18:02 FLAP/static//lib/libFLAP.a
```

**Comment by szaghi** [comment]
> These two tarballs are different: https://github.com/szaghi/FLAP/archive/refs/tags/v1.1.7.tar.gz https://github.com/szaghi/FLAP/releases/download/v1.1.7/FLAP-v1.1.7.tar.gz It looks like the second one is better; the PENF still breaks but I get a library at least:
> 
> ```
> -rw-r--r-- 1 cponder dip 1663862 Dec 22 18:02 FLAP/static//lib/libFLAP.a
> ```
> 
> Also I don't see a corresponding 1.1.8 version posted.

There was an issue with Travis CI, now I have switched to GitHub Actions, and should work fine. The last version is v1.2.5.

Kind regards

**Comment by szaghi** [comment]
I am closing this because it seems to be fixed now. Feel free to re-open it if I am wrong.
