### ISSUE TITLE
install.sh missing for 1.18 tag

### ISSUE THREAD

**Issue by cponder** [szaghi/FLAP#94]
This page
https://github.com/szaghi/FLAP/releases/tag/v1.1.7
posts the customized ```install.sh``` script for the 1.17 tag
```
FLAP-v1.1.7.tar.gz    14.7 MB
install.sh          4.15 KB
Source code (zip)
Source code (tar.gz) 
```
but this page
https://github.com/szaghi/FLAP/releases/tag/v1.1.8
only has source tarballs
```
Source code (zip)
Source code (tar.gz) 
```

**Comment by szaghi** [comment]
@cponder 

Hi, I am very sorry for my delay. I have just pushed a new release (v1.2.5) that should solve this issue.

Thank you for your feedback and help.

Kind regards.

**Comment by szaghi** [comment]
I am closing this because it seems to be fixed now. Feel free to re-open it if I am wrong.
