### ISSUE TITLE
MIs-match in tarball install with install.sh

### ISSUE THREAD

**Issue by cponder** [szaghi/FLAP#95]
Running these instructions
```
wget https://github.com/szaghi/FLAP/releases/download/v1.1.7/install.sh
chmod +x install.sh
./install.sh --download wget 
```
gives this error:
```
Downloaded: 2 files, 15M in 1.9s (7.60 MB/s)
tar: FLAP.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```
It looks like the script needs to encode the version of the tarball.
You could rename it on download
```
wget ... -O  FLAP.tar.gz
```
but I kind of like keeping the version-number visible.
Also there is no ```install.sh``` to go with the 1.1.8 that I can see, I put it in an issue here:
https://github.com/szaghi/FLAP/issues/94

**Comment by szaghi** [comment]
@cponder 

Hi, I am very sorry for my delay. I have just pushed a new release (v1.2.5) that should solve this issue.

Thank you for your feedback and help.

Kind regards.
